version: '3'
networks:
  build:

services:
  builder:
    build:
      context: ./
      dockerfile: Dockerfile.front
      target: builder
    container_name: build-sso
    networks:
      - build
    volumes:
      - ./front:/app/
    environment:
      REACT_APP_ENDPOINT: http://135.125.203.6:8083
